---
title: "PD_book_notes"
author: "Fan Ouyang"
date: "9/20/2017"
output: pdf_document
---

### Routledge International Handbook of Participatory Design

#### chapter 1 -- Intro

##### concept

Participatory Design can be defined as a process of investigating, understanding, reflecting upon, establishing, developing, and supporting mutual learning between multiple participants in collective ‘reflection-inaction’. The participants typically undertake the two principal roles of users and designers where the designers strive to learn the realities of the users’ situation while the users strive to articulate their desired aims and learn appropriate technological means to obtain them.

##### two fundamental aspects
1. it seeks to enable those who will use the technology to have a voice in its design, without needing to speak the language of professional technology design. 
2. a process of mutual learning for both designers and users can inform all participants’ capacities to envisage future technologies and the practices in which they can be embedded.

##### core
1. Design is, fundamentally, about designing futures for actual people. Designing technologies that people rely on in their work shapes, in essential ways, how it is possible for people to do their work and how they experience their working lives.
2. Participation is the core of Participatory Design. genuine’ participation in design (Bødker et al. 2004): we refer to the fundamental transcendence of the users’ role from being merely informants to being legitimate and acknowledged participants in the design process.
  
     2.1 as themselves (respecting their individual and group’s/community’s genuine interests) 
     2.2 with themselves (being concentrated present in order to sense how they feel about an issue, being open towards reflections on their own opinions) 
     2.3 for the task and the project (contributing to the achievement of the shared and agreed-upon goals of the design task and design project at hand
     
3. mutual learning process typically includes ideas and visions for change as they evolve through a design project ‘that reveals goals, defines problems, and indicates solutions, with the aim of designing sustainable uses of IT based on a specific problem within the company’ (Bødker et al. 2004, p. 13).

4. political rationale: a commitment to ensuring that the voices of marginalised groups and communities are heard in decision-making processes

5. practice: what is routinely done in some kind of human activity and how the activity is actually accomplished by the actions of those participating in it

5. collective ‘reflection-in-action’ between multiple participants: process+product. cycle: Workshops with designers and users using techniques such as mock-ups, scenarios, prototypes and various types of design games -> These enable ongoing design experiments to visualise, simulate and experiment with selected elements of envisioned technologies, in use, prior to their development and implementation. -> They enable the participants in the design process to propose, represent, interrogate and reflect on different aspects of the developing design continually throughout that process. 

#### chapter 2 Heritage Having a say
Chapter 2 opens this section with a review of the history and heritage of Participatory Design.

guiding principles:
1. Equalising power relations – finding ways to give voice to those who may be invisible or weaker in organisational power structures.
2. Democratic practices – putting into play the practices and role models for equality among those some call ‘stakeholders’.
3. Situation-based actions – working directly with people in their workplace or homes to understand actions and technologies in actual settings, rather than through formal abstractions.
4. Mutual learning – encouraging and enhancing the understanding of different actors by finding common ground and ways of working.
5. Tools and techniques – that actually, in practical situations, help different actors express their needs and visions
6. Alternative visions about technology – whether it be in the workplace, home, public place or elsewhere – ideas that can generate expressions of equality and democratic practices

#### chapter 3 investigates and elaborates on the design concept

Our aim is to address the question of whether, and in what way, design actually matters for the Participatory Design community

It has to do with participation, with how stakeholders – especially users, developers and planners – cooperatively make or adjust systems, technologies and artefacts in ways which fit more appropriately to the needs of those who are going to use them

We believe that it is important to stress an overarching concern within the ‘Participatory Design tradition’, if we can call it that, on the ‘how’ of designing, i.e. a focus on the practice of design – the nature of design activities, the need for providing means for people to be able to be involved, the need for respect for different voices, the engagement of modes other than the technical or verbal, the concern with improvisation and ongoing evaluation throughout the design process, etc.

##### Part 1: Understanding design – core themes

###### different perspectives

1. Socio-technical systems: This led to the development of an approach to work reorganisation that focused not only on the social subsystem, or the technical subsystem, but rather on how to jointly optimise the joint system. Sociotechnical systems (STS) in organizational development is an approach to complex organizational work design that recognizes the interaction between people and technology in workplaces. The idea was that a work system consisted of both a social system and a technical system interacting with an external environment (both the organisation in which people are working, and the environment within which the firm operates) and that these subsystems needed to be ‘in balance’ in order for an optimal output from the overall system

2. The ‘Scandinavian’ approach to systems design: a political critique of the socio-technical perspective, researchers focused more on the importance of local trade union involvement (Bjerknes et al.1987).

3. ‘soft systems’ analysis and design:  It was one of the first more collaborative Participatory Design methodologies applied in several Participatory Design projects, encouraging professional designers to examine how they could engage ‘users’ in the design process. The approach acknowledged the existence of a variety of stakeholders involved in any project, and their distinct interests, and how this might impact on the design of any system. Thus, the approach provided ways to support dialogue between competing interests and their (partial) resolution, in order to proceed with design. This approach, as used in Participatory Design, may also be seen as an early attempt to work with more narrative design tools – such as scenarios and storyboards, which later became more widely used within the Participatory Design and systems design community more generally.

##### ‘Design’ interventions: inspiration from action research

the approach was: ‘a comparative research on the conditions and effects of various forms of social action and research leading to social action’(Lewin 1946, p. 35). The key steps in the approach involved ‘a spiral of steps, each of which is composed of a circle of planning, action, and fact-finding about the result of the action’

participatory action research. The researcher becomes engaged as one element in a change process, facilitating change, working with the parties concerned, planning change and reflecting on the process of change. the Participatory Design researchers had to recognise that their work must be geared to local needs, and not simply to the production of knowledge for their research peers. In general there were genuine efforts made to reflect upon, and develop, the role of action-oriented research, knowledge production and democratic ideals (Sandberg 1981). It is also possible to think about this early action research orientation serving as a stimulus to later, more ‘designerly’ and ‘reflective’ design research interventions.

##### Design Research and Participatory Design

1. Design science: it is concerned with the study, investigation and accumulation of knowledge about the design process and its constituent operations. It aims to collect, organize and improve those aspects of thought and information which are available concerning design, and to specify and carry out research in those areas of design which are likely to be of value to practical designers and design organizations. (Gregory 1996b, p. 323)

2. Design as rational problem-solving versus reflective practice

- rational problem-solving model: In this approach, design is conceived as a rational search process, where the designer searches a problem space using formal methods in order to achieve a solution to the problem.  Simon suggests ways to transform and reduce this messiness into a stable design space where systems thinking, standard logic and mathematics can be applied

- reflective practice paradigm: we pay attention to the ways professionals in their practice master this messiness and complexity ‘in the swamp’, acknowledging that a stable state is an illusion. The concepts of reflection-in-action and conversations-with-the-material-of-the-situation – as ways of understanding the professional designers’ practice – have become standard references in the Participatory Design community.

3. User-centred design approaches
User-centered design can be characterized as a multi-stage problem-solving process that not only requires designers to analyze and envision the way users are likely to consume a product, but also to validate their assumptions with regard to the user behavior in real world tests.

##### Part 2: Design challenges for Participatory Design

###### Changing technology substrates: from systems to infrastructures
1. Organisational information systems

2. From tinkering and tailoring to appropriation: end-user programming and development/ open-source software packages / groups take over control and shape technologies to their own ends

3. social media

###### Forms of participatory production

1. Open and user-driven innovation
2. end-user participation
3. open production

###### Public participation and social innovation

###### Summary
- this chapter provide in this epilogue a way to ‘open up’ thinking about Participatory Design, a way that goes beyond the traditional design project, that acknowledges heterogeneity and conflicts of interest, as well as new forms of participation and engagement. At the same time it addresses questions of democracy and participation that have been at the core of Participatory Design from the very beginning.

- a desirable shift in the main Participatory Design design thing strategy: from ‘use-before-use’ (Redström 2008), engaging users and ‘prototypes’ in a project and collaboratively exploring potential future use, to ‘design-after-design’, designing for a continuous appropriation and redesign where infrastructuring work becomes the main activity

- to design where a political community, a public characterised by heterogeneity and difference with no shared object of design, is in need of a platform or infrastructure, an ‘agonistic’ public space (Mouffe 2000), not necessarily to solve conflict, but to constructively deal with disagreements – public controversial matters where heterogeneous design things can unfold, and actors engage in alignments of their conflicting objects of design.


#### chapter 4 Ethics Engagement, representation and politics-in-action

##### Basics
1. concept
Ethics, or moral philosophy, has to do with questions relating to how we should live to live a good life (what is a good life?), what kind of society we should have (how to distribute goods and burdens?) and how we should treat others.

Ethics is the enquiry into what is valuable, or, into what is really important, or I could have said Ethics is the enquiry into the meaning of life, or into what makes life worth living, or into the right way of living. 

when it moves from exploring abstract questions about how to live a good life to influencing how people actually do things – then people need to take a stand on various issues that affect them and shape the society in which they live

2. Ethical theories
Normative ethical theories seek answers regarding the standards of moral right and wrong and the grounds for making decisions about what would be the right thing to do; in other words, how we should meet our obligations in a given situation.

Normative ethical theories and the principles on which they build may help address some of the general ethical issues at stake in the making of technologies. They can guide thinking about questions related to autonomy, responsibility, the right to privacy, and so forth. Taking an ethical stance in Participatory Design is about an ethical practice that allows the identification of these issues as they arise in design and use

3. Practical, situated ethics
- one’s ethical self is defined by the ability to recognise the humanity of the other
- Narrative ethics proceeds through constructing and telling one’s own story and comprehending the story of others. This may include decisions such as: What is my story? What is important to relate? What is the best way to express what I consider to be the ethically most relevant material?
- Participants are encouraged to bring forward/argue through stories, and organisers of a deliberation process are required to provide suitable case descriptions. It also resonates well with Participatory Design, which also seeks to build rich representations of practice that are used to collaboratively examine a current situation and envision future, technology-supported practices.

4. Ethics and technology
The crucial point for technology design is that as present possibilities become what actually ‘is’, they become increasingly embedded not just in the technology itself and the social and organisational protocols surrounding its use, but in the specific embodied histories, capacities and social identities of particular people

##### Ethical issues of working with users

- Who do we engage with in a Participatory Design project?
people have the right to influence their own workplace, including the use of computer technology. While identifying the ‘legitimate’ participants in a small project may be straightforward, it can become a problem in complex settings with many participants and multiple dependencies.
- How do we engage with participants?
A core principle of Participatory Design has always been to acknowledge participants as experts in their own work situation. This presumes respect for their expertise as well as mutual trust
- How do we represent participants and their work?
Another principle of Participatory Design is not to tell users what their work is or what it means to them. Producing representations of work can be seen in analogy to the creation of ‘ethnographic accounts’ (and in fact ethnography has an important role in Participatory Design projects).
- What can we offer participants?
In the best of all cases a Participatory Design project results in a well-functioning system or application, amenable to users’ reconfiguring and redesigning to fit evolving uses. But what happens when this is not possible? We are often ‘creating future forms of technology that will not become completely viable within the scope of the project.


##### conclusion
questions to think about related to ethics:
- Do users actually have decision power? If so what kind?
- Does a design method, tool or process recognise and encourage participants’ abilities to learn?
- Does a design method, tool or process guide designers and researchers to analyse and develop their interests and attitude towards participants?
- Does a design method, tool or process include participants’ evaluations not just of what is being designed but of the design process itself, including the opportunities for and process of participation?
- Does a design method, tool or process deal with a justified loss or change of design focus, for example when participants identify problems that require non-information technology solutions while the process was initiated to design information technology)?

#### chapter 5
Chapter 5 re-examines the relationship between ethnography and Participatory Design

#### chapter 6 Methods --  principles and guidelines
The challenge for the design process, in the context of Participatory Design, is therefore how to develop a highly complex piece of technology and at the same time be flexible for learning processes resulting in changes to both the interface and the functionality of the technology throughout the design process – and even beyond
    - think about -- how and when users can have a say : the scope and effect of user participation

##### Basics of Methods 

###### what is *method*? (i.e. normative descriptions)
1. how Participatory Design projects can be set up so that users are enabled to take an active part in
the activities and decisions throughout which new information technology is designed and built
2. a coherent set of organising principles and general guidelines for how to carry out a design process
from start to finish – within a Participatory Design perspective

###### what to *include* in the method description?
1. application area: what type of development activities the method is intended for , in our case, a  web annotation tool
2. perspective: e.g., design should be carried out close to the user so that the user can participate in
design decisions
3. general guidelines: how to conduct and carry out a Participatory Design process
    - techniques: carrying out specific activities. e.g., investigating current practices of use of the web annotation tool
    - tools: concrete instruments supporting the techniques. e.g., facilitating creative workshops where users collaborate with designers on envisioning future work systems
    - organising principles: how to distribute and coordinate work tasks in the design process, how to organise the planned set of interrelated activities, and who to involve in the design

##### Information Technology Design processes
Information technology design is understood as a design process shaping both the technical artefact and its context of use

1. product-oriented: *develop* an information technology system or tool, *perform* this system or tool, *analyze* current situations, and *design* for the future change
2. process-oriented: *manage* the process, *evaluate* the current situations, and *plan* the future


##### *Four* Participatory Design methods
1. STEPS: Software Technology for Evolutionary Participatory Systems Development (*maybe fit for our project*)
     - application area: software development for socially embedded systems with a special emphasis on co-development of usage and technology
     - perspective: 
          1. to facilitate the co-development of usage and software as a joint design and exploratory learning process; a software development cycle is established under the joint responsibility of users and designers
          2. development process is designed as an iterative one, where evolutionary
prototypes of the software are the central design artefact mediating a mutual learning process
          3. adapting the process according to the evolving requirements; a paradigm change in software engineering from a ‘product-oriented paradigm’ to a ‘process-oriented paradigm
          4. Designers and users together decide on the scope of the revision, and on the specific tools and techniques applied for the collaborative design resulting in additional intermediary products.
          5. requirements need to be gradually established in anticipative, constructive and evaluative steps carried out by designers and users in interaction; design is not understood as the achievement of predefined goals, but is guided by insights emerging in the actual process
          
2. MUST (related to  business needs and conditions for information technology projects; *maybe not fit for our project*)
- concept: a business-oriented and socially sensitive approach that takes into consideration the specific organisational context as well as first-hand knowledge of users’ work practices, and it allows all stakeholders – users, management and other staff – to participate in the process.
- principles
     1. coherent vision
     2. genuine user participation
     3. firsthand experience with users' practices
     4. anchoring visions
     
3. CESD: Cooperative Experimental System Development 
- basic concept: tool perspective, make systems act as good tools for users
- perspectives
      1. it actively pursues a strategy of utilising experimental approaches in the analysis of existing practices
      2. it applies the cooperative and experimental techniques also in the parts of the project where the main concern is technical design and implementation, i.e. designers with Participatory Design competencies and technical skilled designers cooperate throughout a project
      3. it pays explicit attention to the transformation of loosely specified design artefacts, such as mock-ups and prototypes, into properly engineered and documented computer systems.
- activities: workshop-based cooperative experiments and interventions. 

4. Use-oriented design (*may be fit for our project*)
- basic concept: emphasising the use context as the overall context of the information technology
design – including the evaluation of the quality of the system
- this approach is that users may expand the space of design ideas because their imagination will be based on their experiences. The approach is explorative, aiming to postpone the decision about the design problem so that users and designers can collaborate (or negotiate) on the problem setting after they have got to know each other
- guideline
     1. guidelines for this approach include a range of techniques and tools for mutual learning, where the users learn enough about technical possibilities to develop a technical imagination
     2. users should not be forced to apply a technical-oriented language when describing their work
     3. The process is organised so that the users and designers discuss (and negotiate) the problem setting and the solution, both being aware that they have interests in the future solution.
- iterative cycle of participatory design process
     1. real life problem situation
     2. understanding practice
     3. identifying needs, wishes
     4. describing requirements
     5. concretizing, materializing
     6. testing, evaluating
     
##### essential characteristics of PD methods
- having a say

having something to say as well as affecting the outcome of an activity with what you say – i.e. having an influence; speaking thier own language

- mutual learning 
mutual learning implies that designers learn about the use context from the users, but also
that the users learn about the technical possibilities from the designers


**in our project** designers understand how this tool will be used in classroom contexts; teachers know the possible functions of this tool from the designers

- co-realisation
1. there are different ways of visualising possible solutions, with *prototyping* as the most important technique; enable co-construction and learning through sharing concrete experiences of a new imagined artefact
2. Knowledge domains for mutual learning (*useful p.133-135*)

|                     |current practices            | practices with new technology  | technological options  |
|---------------------|:---------------------------:|:------------------------------:|-----------------------:|
| abstract knowledge  | relevant descriptions       | visions and design proposals   | overview of options    |
| concrete experience | experience with practices   |experience using new technology | experience with options|

3. stepwise
understand the situation -> make a design suggestion -> analyze and evaluate -> understand the new situation -> make this a basis for a new design suggestion
4. design after design 
provide users with the tools to develop or refine their tools themselves


#### chapter 7 Tools and techniques

##### value: practice of participation (the tell-make-enact framework)
1. Telling activities as drivers for participation

**for our project** consider these steps: 

a. in the first meeting, stress that teachers, designers, researchers lead in deciding how the activities play out over time (mutual leanring process); because teachers have the firsthand experiences with student learning, their input is very important for us; teachers are not expecting to use technical languages, they should use their own language
b. before our workshop, hand over descriptions of prototype (what has been done, how to use this tool, what functions it has, what is going to be done in the future) to teachers, let teachers try out the prototype, stressing that the mutual interests in ongoing revisions of the tool (design after design); 
c. when use the tool, teachers can learn more about the tool, have a technical imagination and concrete ideas about the functions of the tool, reflection on the use of the tool in authentic learning process, identify wishes and needs for future tool revisions
d. in our workshop, let teachers to talk about their experiences with the tool, also let them talk an ideal tool they want; create some joint activities (e.g., role playing of teachers and students in learning in different situations/subjects) for teachers and designers to work on; finally talk about what can be done to move towards the ideal vision of the tool

2. The making of things as a means of design participation
- participatory prototyping: using mock-ups in the early stages of the established design process; users can actively participate in the design process by actually doing
- probes as a means of exploring experience: Probes refers to a design-led approach that invites people to reflect on and express their experiences, feelings and attitudes in forms and formats that provide inspiration for designers 
- generative tools for co-designing: are used in the front end of design to help non-designers to imagine and express their own ideas about how they want to live, work and play in the future (notebook, reflective journal, concept map, think-out-loud)

3. Participation through enacting possible futures
activities where one or more people imagine and act out possible futures by trying things out (by use of the body) in settings that either resemble or are where future activities are likely to take place.

   
#####  relationships between telling, making and enacting
- What are the best entry points into the iterative processes of participatory designing?
- How do you decide in what order to conduct the activities? Is it better to have participants do the making activities before enacting? Or vice versa?
- Should the participants or the researchers lead in deciding how the activities play out over time?
- Do the relationships between making, telling and enacting change at different phases of the design process? If so, how?
- Do the artefacts of the Participatory Design process change across the different stages of the
design process? If so, how?


##### further exploration, application and refinement
- Analysis can focus on the artefact, the story, the enactment and/or the interplay between artefact, story and enactment

#### Chapter 8
Chapter 8 recognises community-based Participatory Design as a distinctive field of Participatory Design research.

#### Chapter 9
Chapter 9 provides one of this section’s three cases of practical large-scale applications of Participatory Design.

#### Chapter 10
Chapter 10 describes the second Artful Integration Award initiative.

#### Chapter 11
Chapter 11 presents the ACTION for Health project that was initiated in 2003 and ended in 2008.


Future readings
PD conference proceedings from 1990 until today are available from http://pdcproceedings.org
